### ISSUE TITLE
Problem comparing JSON fields with only one value

### ISSUE THREAD

**Issue by ethieblin** [farshidtz/wot-discovery-testing#24]
The testing TD contains an array with only one value for the "security" field, our implementation relies on JSON-LD framing which transforms single values into string and not arrays.
According to both the [json-ld context](https://github.com/w3c/wot-thing-description/blob/537d223f0ed9df0f601d239942c930c42b406191/context/td-context-1.1.jsonld#L164) and the [JSON schema](https://github.com/w3c/wot-thing-description/blob/537d223f0ed9df0f601d239942c930c42b406191/validation/td-json-schema-validation.json#L28), both should be accepted: array or single string.

However the testing tool sends an error because it expects:
  ```
    "security": [
	    "nosec_sc"
    ],
  ```
and it is different from
  ```
    "security": "nosec_sc",
  ```

**Comment by farshidtz** [comment]
The comparison function simply compares serialized JSONs:
https://github.com/farshidtz/wot-discovery-testing/blob/c34c6d903f044b581f938df1d2ec0982db8e6f11/directory/utilities.go#L174-L185

Have to think how we can assert that two objects are semantically equal.

**Comment by Murloc6** [comment]
@farshidtz A way to do it is to use the expanded format for each td, and then use a jsondiff library (for example : https://github.com/nsf/jsondiff) to compare. Then this issue will be solved.

We studied which JSON-LD library fits the most of the current standard, and we concluded that jsonld.js (https://github.com/digitalbazaar/jsonld.js) is the best one. Nevertheless, there is no Go interface, but the node script can be called from your Go application I guess (we did a similar hack for our SparTDD implementation which is using Python).

If you look at this [playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22Jane%20Doe%22%7D&frame=%7B%7D&context=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%7D) and compare with [this one](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%5B%22Jane%20Doe%22%5D%7D&frame=%7B%7D&context=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%7D), the expanded format are the exact same for the following JSON-LD documents:
```jsonld
{
  "@context": "http://schema.org/",
  "@type": "Person",
  "name": ["Jane Doe"]
}
```
and
```jsonld
{
  "@context": "http://schema.org/",
  "@type": "Person",
  "name": "Jane Doe"
}
```

and the expanded format for both is:
```jsonld
[
  {
    "@type": [
      "http://schema.org/Person"
    ],
    "http://schema.org/name": [
      {
        "@value": "Jane Doe"
      }
    ]
  }
]
```

**Comment by farshidtz** [comment]
Thanks for the explanation. I tried [this library](https://github.com/piprate/json-gold) and wanted to compare expanded outputs but I was getting the following error which I could not solve:
```
invalid value object: Attempt to add illegal key to value object: hasInstanceConfiguration
```

I will go with a simplified approach and make a PR.
