### ISSUE TITLE
Cannot get report with last commit

### ISSUE THREAD

**Issue by ethieblin** [farshidtz/wot-discovery-testing#38]
We are running the testing tool with the docker image.

The command we launch is:
`docker run --rm -v $(pwd)/report:/report wot-discovery-testing --server=OUR-TDD-SERVER-URL`

The command finishes fine, but no report can be found in the mounted volume folder.
Thank you for looking into this.

**Comment by farshidtz** [comment]
The path inside the container should be `/home/report`. I will update the readme.

Try:
```
docker run --rm -v $(pwd)/report:/home/report wot-discovery-testing --server=OUR-TDD-SERVER-URL
```

**Comment by ethieblin** [comment]
It worked, thanks :)
