### ISSUE TITLE
Error comparing the @contexts

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [farshidtz/wot-discovery-testing#9]
The Directory injects in the TDs the registration information (this is taken into account in the tests). However, the @context is also modified (since the @context of discovery must be added to the terms related are compliant with the ontology). Currently, the tests require that a pre-registered TD has the same context as a registered one, which can not be true.

I can create a PR that removes the comparison of these contexts.

**Comment by farshidtz** [comment]
For now, I've set it to ignore context; see #10.

We have to revisit this once https://github.com/w3c/wot-discovery/issues/291 is reolved.
